### ISSUE TITLE
Ambiguous import google/protobuf/***

### ISSUE THREAD

**Issue by urionz** [bufbuild/intellij-buf#112]
The buf plugin conflicts with the official protobuffers plugin

**Comment by srikrsna-buf** [comment]
Hey! I can't seem to replicate the issue, would you be able to create a sample project and share that with us? Also I tried in Intellij Ultimate 2023.1.2, could you tell us the IDE and version that you are seeing this in? It should not change based on that but just in case.

**Comment by urionz** [comment]
> Hey! I can't seem to replicate the issue, would you be able to create a sample project and share that with us? Also I tried in Intellij Ultimate 2023.1.2, could you tell us the IDE and version that you are seeing this in? It should not change based on that but just in case.

IDE: goland 2022.3.1
