### ISSUE TITLE
Aggressive Autosaving Causes File Reformat

### ISSUE THREAD

**Issue by Kryan90** [bufbuild/intellij-buf#133]
This plugin causes auto-save to trigger immediately after I stop typing when a proto file is open but not in focus

Example:
Have a .go file open, open a .proto file -> split and move right
Add a new line to the .go file, auto-save is triggered and go fmt runs removing the newline

Similar to this issue, but I confirmed it is specifically the buf plugin causing it for me: https://youtrack.jetbrains.com/issue/WEB-54949/auto-save-as-soon-as-stop-typing

**Comment by Kryan90** [comment]
Unchecking these two settings seems to fix the undesired behavior 
![image](https://github.com/bufbuild/intellij-buf/assets/18740821/3af0e01f-87ec-4248-b558-fc067d249176)

**Comment by bufdev** [comment]
We'll check this out, thanks for the bug report.

**Comment by Kryan90** [comment]
buf plugin: 0.1.5
GoLand 2023.2 - Build #GO-232.8660.185, built on July 25, 202

It seems to happen within specific contexts, for example inside a function body or struct definition. I took a short video to demonstrate the behavior

https://github.com/bufbuild/intellij-buf/assets/18740821/56f4aa40-5587-4ad5-9ce8-a7ae2f17f27f
