### ISSUE TITLE
Register BUF configuration schemas

### ISSUE THREAD

**Issue by Goldziher** [bufbuild/intellij-buf#144]
Hi, I am working on integrating buf and installed the intellij plugin. I suggest that the plugin is updated to register the JSON schemas for the yaml files - so these are validated by the IDE.

**Comment by pkwarren** [comment]
Related to https://github.com/bufbuild/buf/issues/1413 - if we publish schemas to schemastore, this should also make things work out of the box in the IntelliJ plugin.

**Comment by Goldziher** [comment]
> Related to https://github.com/bufbuild/buf/issues/1413 - if we publish schemas to schemastore, this should also make things work out of the box in the IntelliJ plugin.

Exactly- it will allow validating the configs based on versions

**Comment by stefanvanburen** [comment]
See https://github.com/bufbuild/buf/issues/1413#issuecomment-1764417864 - I've published initial support for these files upstream. I'm not 100% sure on how often IntelliJ pulls down the latest SchemaStore schemas, but hopefully soon.

If you see any issues with the schemas, please report those upstream and feel free to tag me!

**Comment by Goldziher** [comment]
> See [bufbuild/buf#1413 (comment)](https://github.com/bufbuild/buf/issues/1413#issuecomment-1764417864) - I've published initial support for these files upstream. I'm not 100% sure on how often IntelliJ pulls down the latest SchemaStore schemas, but hopefully soon.
> 
> If you see any issues with the schemas, please report those upstream and feel free to tag me!

i reported one issue in the linked comment
