### ISSUE TITLE
didn't work in Goland 2022.1.1

### ISSUE THREAD

**Issue by younglifestyle** [bufbuild/intellij-buf#17]
vsc plugin works fine，but goland plugin didn't work

**Comment by timostamm** [comment]
Thanks for the issue.

I am running GoLand 2022.1.1 with version 1.1 of this plugin. Formatting, linting and syntax highlighting have been working well for me.

Could you provide some details on what didn't work for you?

**Comment by younglifestyle** [comment]
here is a screenshot of the IDE

![image](https://user-images.githubusercontent.com/19261307/171141605-f7330772-a1cd-42d8-b450-6975af0146af.png)

![image](https://user-images.githubusercontent.com/19261307/171141844-ccff1aa5-526a-4b21-9fb8-f645c9ef9c9c.png)

**Comment by timostamm** [comment]
The screenshot looks correct. Did you expect to see a lint error?

You will need a [buf.yaml](https://docs.buf.build/configuration/v1/buf-yaml) file or a [buf.work.yaml](https://docs.buf.build/configuration/v1/buf-work-yaml) file at the root of the project, just as with `buf`.

**Comment by younglifestyle** [comment]
> The screenshot looks correct. Did you expect to see a lint error?
> 
> You will need a [buf.yaml](https://docs.buf.build/configuration/v1/buf-yaml) file or a [buf.work.yaml](https://docs.buf.build/configuration/v1/buf-work-yaml) file at the root of the project, just as with `buf`.

yes i would like to see lint error，I use the official example [weather.proto](https://github.com/bufbuild/buf-examples/blob/main/linting/bad/acme/weather/v1/weather.proto)，but still can't see it, I can see lint error when I execute it manually
![image](https://user-images.githubusercontent.com/19261307/171311886-6082fe78-ea6e-4048-9f29-f1aa606b9f3f.png)

**Comment by younglifestyle** [comment]
> Tracking this internally in [TCN-148](https://linear.app/bufbuild/issue/TCN-148).

thank you very much，I see it
