### ISSUE TITLE
Reformat Code on proto file introduces newlines at 8192 char intervals

### ISSUE THREAD

**Issue by timw** [bufbuild/intellij-buf#180]
When a proto file larger than 8192 chars has Reformat Code run, newlines are introduced after each 8192 chars.

This does not happen to the file when `buf format` is run on the same file.

This obviously can break the syntax of the proto file in various ways, which subsequently breaks `protoc` compilation and future `buf format` executions.

In the latter case, there's an additional issue that a Reformat Code run on a file with invalid syntax fails and clears the IntelliJ editor buffer.
(e.g. `buf format` would report a `Failure: filename.proto:245:8: syntax error`)

It looks like the output of `buf format` is being read from `stdout` and joined with separating newlines at https://github.com/bufbuild/intellij-buf/blob/main/src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt#L66 , when in this case it should probably just be concatenated verbatim without separators.

**Comment by pkwarren** [comment]
Thank you @timw for the report - this will be fixed in the v0.3.1 version of the plugin, which should be published through the JetBrains marketplace in the next few days.
