### ISSUE TITLE
When the file is not added to git, the contents are emptied on format

### ISSUE THREAD

**Issue by godcong** [bufbuild/intellij-buf#273]
![image](https://github.com/user-attachments/assets/1aaff930-99a5-400c-b4d8-879c63419881)

↑↑↑ Choose like the picture ↑↑↑

When you create a new proto file that hasn't been added to git yet.
When you run Goland's Format, it clears out all the content you've edited.

If the file is added to git, it works fine.

[Expect]
Don't delete what I'm trying to edit

**Comment by timostamm** [comment]
Apparently this is not related to the linked issue after all, but we're looking into it.

**Comment by pkwarren** [comment]
@godcong - Thank you for the bug report. This should now be resolved in version 0.4.2 of the plugin.
